# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170522_1250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
