# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170522_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, default=''),
        ),
    ]
