# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170522_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default=b'<django.db.models.query_utils.DeferredAttribute object at 0x103564e50>', max_length=33),
        ),
    ]
