# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170524_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='datum',
            field=models.CharField(default='NAD27', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
