# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170524_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
