# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='photo',
        ),
    ]
