# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170602_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='biop',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
